version: "2"
plugins:
  # --
  # 😞
  # @see https://github.com/seattlerb/ruby_parser/issues/255
  # This can break on some Regexps.
  #   So it's disabled.
  # --
  duplication:
    enabled: false
  rubocop:
    # --
    # 🤨
    # We must set the default version we want.
    #   Sometimes CodeClimate lags.
    # --
    channel: rubocop-0-52
    enabled: true
    config:
      file: .rubocop.yml
ratings:
  paths:
  - "spec/tests/**.rb"
  - "lib/**.rb"
